let word_list = [["大", "dà", "big", "HSK 1 Adjectives"],
["多", "duō", "many", "HSK 1 Adjectives"],
["高兴", "gāoxìng", "happy", "HSK 1 Adjectives"],
["好", "hǎo", "good", "HSK 1 Adjectives"],
["冷", "lěng", "cold", "HSK 1 Adjectives"],
["漂亮", "piàoliang", "pretty", "HSK 1 Adjectives"],
["热", "rè", "hot", "HSK 1 Adjectives"],
["少", "shǎo", "few", "HSK 1 Adjectives"],
["小", "xiǎo", "small", "HSK 1 Adjectives"],
["不", "bù", "no&#11828 not", "HSK 1 Adverbs"],
["没有", "méiyǒu", "did not", "HSK 1 Adverbs"],
["很", "hěn", "very", "HSK 1 Adverbs"],
["太", "tài", "too", "HSK 1 Adverbs"],
["都", "dōu", "all", "HSK 1 Adverbs"],
["会", "huì", "can&#11828 know to", "HSK 1 Auxiliary Verbs"],
["能", "néng", "can&#11828 be able to", "HSK 1 Auxiliary Verbs"],
["想", "xiǎng", "would like to", "HSK 1 Auxiliary Verbs"],
["这", "zhè", "this", "HSK 1 Demonstrative Pron."],
["那", "nà", "that", "HSK 1 Demonstrative Pron."],
["多少", "duōshǎo", "how much", "HSK 1 Interrogative Pron."],
["几", "jǐ", "how many&#11828 a few", "HSK 1 Interrogative Pron."],
["哪", "nǎ", "which", "HSK 1 Interrogative Pron."],
["哪儿", "nǎr", "where", "HSK 1 Interrogative Pron."],
["什么", "shénme", "what&#11828 why", "HSK 1 Interrogative Pron."],
["谁", "shéi", "who", "HSK 1 Interrogative Pron."],
["怎么", "zěnme", "how", "HSK 1 Interrogative Pron."],
["怎么样", "zěnmeyàng", "how about", "HSK 1 Interrogative Pron."],
["本", "běn", "[measure word for books]", "HSK 1 Measure Words"],
["个", "gè", "[measure word for people]", "HSK 1 Measure Words"],
["块", "kuài", "[measure word for pieces]", "HSK 1 Measure Words"],
["岁", "suì", "years old", "HSK 1 Measure Words"],
["些", "xiē", "some", "HSK 1 Measure Words"],
["一点儿", "yīdiǎnr", "a little", "HSK 1 Measure Words"],
["爸爸", "bàba", "father; dad", "HSK 1 Nouns"],
["北京", "Běijīng", "Beijing", "HSK 1 Nouns"],
["杯子", "bēizi", "cup", "HSK 1 Nouns"],
["菜", "cài", "vegetable", "HSK 1 Nouns"],
["茶", "chá", "tea", "HSK 1 Nouns"],
["出租车", "chūzūchē", "taxi", "HSK 1 Nouns"],
["点", "diǎn", "point&#11828 dot&#11828 spot", "HSK 1 Nouns"],
["电脑", "diànnǎo", "computer", "HSK 1 Nouns"],
["电视", "diànshì", "television", "HSK 1 Nouns"],
["电影", "diànyǐng", "movie", "HSK 1 Nouns"],
["东西", "dōngxi", "thing", "HSK 1 Nouns"],
["儿子", "érzi", "son", "HSK 1 Nouns"],
["饭店", "fàndiàn", "restaurant", "HSK 1 Nouns"],
["飞机", "fēijī", "airplane", "HSK 1 Nouns"],
["分钟", "fēnzhōng", "minute", "HSK 1 Nouns"],
["狗", "gǒu", "dog", "HSK 1 Nouns"],
["汉语", "hànyǔ", "mandarin Chinese", "HSK 1 Nouns"],
["后面", "hòumiàn", "behind", "HSK 1 Nouns"],
["家", "jiā", "home", "HSK 1 Nouns"],
["今天", "jīntiān", "today", "HSK 1 Nouns"],
["老师", "lǎoshī", "teacher", "HSK 1 Nouns"],
["里面", "lǐmiàn", "inside", "HSK 1 Nouns"],
["妈妈", "māma", "mother; mom", "HSK 1 Nouns"],
["猫", "māo", "cat", "HSK 1 Nouns"],
["米饭", "mǐfàn", "rice", "HSK 1 Nouns"],
["明天", "míngtiān", "tomorrow", "HSK 1 Nouns"],
["名字", "míngzi", "name", "HSK 1 Nouns"],
["年", "nián", "year", "HSK 1 Nouns"],
["女儿", "nǚ ér", "daughter", "HSK 1 Nouns"],
["朋友", "péngyou", "friend", "HSK 1 Nouns"],
["苹果", "píngguǒ", "apple", "HSK 1 Nouns"],
["钱", "qián", "money", "HSK 1 Nouns"],
["前面", "qiánmiàn", "front", "HSK 1 Nouns"],
["人", "rén", "person", "HSK 1 Nouns"],
["上", "shàng", "up", "HSK 1 Nouns"],
["商店", "shāngdiàn", "store", "HSK 1 Nouns"],
["上午", "shàngwǔ", "morning", "HSK 1 Nouns"],
["时候", "shíhou", "time", "HSK 1 Nouns"],
["书", "shū", "book", "HSK 1 Nouns"],
["水", "shuǐ", "water", "HSK 1 Nouns"],
["水果", "shuǐguǒ", "fruit", "HSK 1 Nouns"],
["天气", "tiānqì", "weather", "HSK 1 Nouns"],
["同学", "tóngxué", "shoolmate", "HSK 1 Nouns"],
["下", "xià", "down", "HSK 1 Nouns"],
["先生", "xiānsheng", "sir", "HSK 1 Nouns"],
["现在", "xiànzài", "now", "HSK 1 Nouns"],
["小姐", "xiǎojiě", "Miss", "HSK 1 Nouns"],
["下午", "xiàwǔ", "afternoon", "HSK 1 Nouns"],
["星期", "xīngqī", "week", "HSK 1 Nouns"],
["学生", "xuéshēng", "student", "HSK 1 Nouns"],
["学校", "xuéxiào", "school", "HSK 1 Nouns"],
["衣服", "yīfu", "cloth", "HSK 1 Nouns"],
["医生", "yīshēng", "doctor", "HSK 1 Nouns"],
["医院", "yīyuàn", "hospital", "HSK 1 Nouns"],
["椅子", "yǐzi", "chair", "HSK 1 Nouns"],
["月", "yuè", "month", "HSK 1 Nouns"],
["中国", "Zhōngguó", "China", "HSK 1 Nouns"],
["中午", "zhōngwǔ", "noon", "HSK 1 Nouns"],
["桌子", "zhuōzi", "desk", "HSK 1 Nouns"],
["字", "zì", "character", "HSK 1 Nouns"],
["昨天", "zuótiān", "yesterday", "HSK 1 Nouns"],
["一", "yī", "one", "HSK 1 Numerals"],
["二", "èr", "two", "HSK 1 Numerals"],
["三", "sān", "three", "HSK 1 Numerals"],
["四", "sì", "four", "HSK 1 Numerals"],
["五", "wǔ", "five", "HSK 1 Numerals"],
["六", "liù", "six", "HSK 1 Numerals"],
["七", "qī", "seven", "HSK 1 Numerals"],
["八", "bā", "eight", "HSK 1 Numerals"],
["九", "jiǔ", "nine", "HSK 1 Numerals"],
["十", "shí", "ten", "HSK 1 Numerals"],
["号", "hào", "[day number in a date]&#11828 number (in a series)", "HSK 1 Numerals"],
["爱", "ài", "to love", "HSK 1 Verbs"],
["吃", "chī", "to eat", "HSK 1 Verbs"],
["读", "dú", "to read", "HSK 1 Verbs"],
["工作", "gōngzuò", "to work", "HSK 1 Verbs"],
["喝", "hē", "to drink", "HSK 1 Verbs"],
["回", "huí", "to return", "HSK 1 Verbs"],
["叫", "jiào", "to call&#11828 to be called", "HSK 1 Verbs"],
["开", "kāi", "to open", "HSK 1 Verbs"],
["看", "kàn", "to look (at)", "HSK 1 Verbs"],
["看见", "kànjiàn", "to see", "HSK 1 Verbs"],
["来", "lái", "to come", "HSK 1 Verbs"],
["没有", "méiyǒu", "to not have", "HSK 1 Verbs"],
["买", "mǎi", "to buy", "HSK 1 Verbs"],
["请", "qǐng", "please", "HSK 1 Verbs"],
["去", "qù", "to go", "HSK 1 Verbs"],
["认识", "rènshi", "to be familiar with", "HSK 1 Verbs"],
["是", "shì", "to be (am&#11828 is&#11828 are)", "HSK 1 Verbs"],
["睡觉", "shuìjiào", "to sleep", "HSK 1 Verbs"],
["说", "shuō", "to say. to speak", "HSK 1 Verbs"],
["听", "tīng", "to listen (to)", "HSK 1 Verbs"],
["下雨", "xiàyǔ", "to rain", "HSK 1 Verbs"],
["写", "xiě", "to write", "HSK 1 Verbs"],
["谢谢", "xièxie", "thank you; to thank", "HSK 1 Verbs"],
["喜欢", "xǐhuān", "to like", "HSK 1 Verbs"],
["学习", "xuéxí", "to study", "HSK 1 Verbs"],
["有", "yǒu", "to have", "HSK 1 Verbs"],
["再见", "zàijiàn", "good-bye", "HSK 1 Verbs"],
["住", "zhù", "to live (in/at)", "HSK 1 Verbs"],
["做", "zuò", "to do", "HSK 1 Verbs"],
["坐", "zuò", "to sit", "HSK 1 Verbs"],
["你", "nǐ", "you", "HSK 1 Personal Pronouns"],
["他", "tā", "he&#11828 him", "HSK 1 Personal Pronouns"],
["她", "tā", "she&#11828 her", "HSK 1 Personal Pronouns"],
["我", "wǒ", "I&#11828 me", "HSK 1 Personal Pronouns"],
["我们", "wǒmen", "we&#11828 us", "HSK 1 Personal Pronouns"],
["的", "de", "[structural particle]", "HSK 1 Particles"],
["了", "le", "[aspectual particle]", "HSK 1 Particles"],
["吗", "ma", "[question particle]", "HSK 1 Particles"],
["呢", "ne", "[question particle]", "HSK 1 Particles"],]